---


- name: Check if Kiali Exists
  stat:
     path: "{{ kiali.dw_directory }}/deploy-kiali-to-kubernetes.sh"
  register: kiali_information

- name: Download Kiali Script
  get_url:
     url: "{{ kiali.dw_url }}"
     dest: "{{ kiali.dw_directory }}/deploy-kiali-to-kubernetes.sh"
     mode: 0777
  when: kiali_information.stat.exists == False

- name: Install Kiali
  shell: |
    deploy-kiali-to-kubernetes.sh