---
# vars file for everis-paas-demo
mac_os:
  sdk_version: '238.0.0'
  arc: 'x86_64'

gcp:
  project_id: everis-paas-demo-2
  zone: 'us-central1-a'
  resources: ['compute.googleapis.com' ,'container.googleapis.com' ,'cloudbuild.googleapis.com']
  k8s_cluster_name: demo-paas
  k8s_min_nodes: 1
  k8s_man_nodes: 4
  k8s_num_nodes: 2
  k8s_admin_sa: demo-paas
  k8s_admin_binding: root-sa-binding
  k8s_tiller_sa: tiller
  k8s_tiller_binding: tiller
  sdk_working_directory: /home

demo:
  namespaces: 'default'


  helm:
    dw_url: https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get