apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: 2019-02-07T21:16:56Z
  generation: 1
  labels:
    app: {{ api-name-v1 }}
    version: v1
  name: {{ api-name-v1 }}
  namespace: {{ demo.namespaces }}
  resourceVersion: "2908194"
  uid: b2a92eb9-2b1d-11e9-b70a-42010a8002be
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ api-name-v1 }}
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ api-name-v1 }}
        version: v1
    spec:
      containers:
      - image: gcr.io/{{ project_id }}/{{ api-name-v1 }}:1.0.0
        imagePullPolicy: IfNotPresent
        name: {{ api-name-v1 }}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-02-07T21:16:56Z
    lastUpdateTime: 2019-02-07T21:16:56Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-02-07T21:16:56Z
    lastUpdateTime: 2019-02-07T21:17:00Z
    message: ReplicaSet "gc-example-a-79cfcd89f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
