apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ api.name.v1 }} 
  name: {{ api.name.v1 }}
  namespace: {{ default }}
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ api.name.v1 }}
  sessionAffinity: None
  type: ClusterIP
