apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gc-example-a
  namespace: default
spec:
  hosts:
  - "gc-example-a.gdefault.svc.cluster.local"
  gateways:
  - gc-example-a-gateway
  http:
  - match:
    - uri:
        prefix: /endpoint
    route:
    - destination:
        host: "example.svc.default.cluster.local"
        subset: v1
    corsPolicy:
      allowOrigin:
      - example.com
      allowMethods:
      - POST
      - GET
      allowCredentials: false
      allowHeaders:
      - X-Foo-Bar
      maxAge: "1d"    