---
- name: Install CRDs for istio support
  shell: |
    kubectl apply \
    --filename \
    https://github.com/knative/serving/releases/download/v0.4.0/istio-crds.yaml

- name: Deploy Istio system
  shell: |
    kubectl apply \
    --filename \
    https://github.com/knative/serving/releases/download/v0.4.0/istio.yaml
  register: istio_install_result
  until: istio_install_result.rc == 0
  retries: 2
  delay: 10

- name: Query labels on default namepsaces
  shell: |
    kubectl get ns -l 'istio-injection=enabled' -o name
  register: namespace_labels 

- name: Label default namespace for envoy injection
  shell: |
    kubectl label namespace \
    default istio-injection=enabled
  when: ('namespace/'+demo.namespaces not in namespace_labels.stdout.split())